name: aoc2022
version: 0.1.0.0
#synopsis:
#description:
homepage: https://github.com/raymond-h/advent-of-code-2022#readme
license: BSD3
author: Raymond Hammarling
maintainer: raykay.rh@gmail.com
copyright: 2022 Raymond Hammarling
category: Web
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - containers
  - text
  - megaparsec
  - pretty-simple
  - recursion-schemes
  - array
  - comonad

default-extensions:
  - OverloadedStrings

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  aoc2022:
    source-dirs: app
    main: Main.hs
    dependencies:
      - aoc2022

tests:
  aoc2022-test:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - aoc2022
      - hspec
      - QuickCheck
      - generic-random
